- shape 행과열 크기를 나타낼 때
 -- np.shape
- ndim  차원수를 나타낼 때
 -- np.ndim


In [9]:
import numpy as np

array1 = np.array([1,2,3,4])       # 1차원
array11 = np.array([[1,2,3,4]])    # 2차원
array111 = np.array([[[1,2,3,4]]]) # 3차원
# (4,) -> (1,4)
array2 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,3,2,1]])
print('array1 크기:',array1.shape)
print('array1 차원수:',array1.ndim)
print('array11 크기:',array11.shape)
print('array11 차원수:',array11.ndim)
print('array111 크기:',array111.shape)
print('array111 차원수:',array111.ndim)
print('array2 크기:',array2.shape)
print('array2 차원수:',array2.ndim)

array1 크기: (4,)
array1 차원수: 1
array11 크기: (1, 4)
array11 차원수: 2
array111 크기: (1, 1, 4)
array111 차원수: 3
array2 크기: (3, 4)
array2 차원수: 2


### reshape
- 차원과 크기(행*열)를 변경하는 함수

In [21]:
# 기존
# a = [1,2,3,4,5,6,7,8,9]
array1 = np.arange(10)
# \n -> 엔터
print('array1 \n',array1)
print('array1 shape \n',array1.shape)

# reshape(행,열)
array2 = array1.reshape(2,5)
array3 = array1.reshape(5,2)
array4 = array1.reshape(10,1)
array5 = array1.reshape(1,10)
print('array2 형태 \n',array2)
print('array3 형태 \n',array3)
print('array4 형태 \n',array4)
print('array5 형태 \n',array5)
# 5,2 / 10,1 / 1,10


array1 
 [0 1 2 3 4 5 6 7 8 9]
array1 shape 
 (10,)
array2 형태 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 형태 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4 형태 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
array5 형태 
 [[0 1 2 3 4 5 6 7 8 9]]
