### Numpy ndarray

In [1]:
# 라이브러리 연결
import numpy as np

# numpy 만드는 방법
#array([])
list1 = [1,2,3]  # 리스트
array1 = np.array([1,2,3])
array2 = np.array(list1)

print('type',type(list1))
print('array1 type',type(array1))
print('array2 type',type(array2))
print('array1 형태',array1.shape)
print('array2 형태',array2.shape)
print('array1 차원수',array1.ndim)


type <class 'list'>
array1 type <class 'numpy.ndarray'>
array2 type <class 'numpy.ndarray'>
array1 형태 (3,)
array2 형태 (3,)
array1 차원수 1


In [ ]:
# 차이점을 아는것이 엄청 중요
# array1 (3,)  1차원
# array1 (1,3) 2차원

In [2]:
array2 = np.array([[1,2,3]])
print('array2 type',type(array2))
print('array2 형태',array2.shape)
print('array2 차원수',array2.ndim)

array2 type <class 'numpy.ndarray'>
array2 형태 (1, 3)
array2 차원수 2


In [8]:
array3 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

# 형태(행,열) shape
# 차원수 ndim
print('형태',array3.shape)
print('차원수',array3.ndim)



형태 (3, 3)
차원수 2


In [9]:
# 형태 (2,4)
array3 = np.array([[1,2,3,4],
                  [5,6,7,8]])

# 형태(행,열) shape
# 차원수 ndim
print('형태',array3.shape)
print('차원수',array3.ndim)

형태 (2, 4)
차원수 2


### reshape
- 차원과 크기를 변경하는 함수

In [23]:
array1 = np.arange(10)
print('array1 \n', array1)
# 차원변경  reshape
# 1*10 , 2*5, 5*2, 10*1
#reshape(행,열)
array2 = array1.reshape(2,5)
array3 = array1.reshape(5,2)
array4 = array1.reshape(10,1)
# -1
array5 = array1.reshape(5,-1)
print('array2 형태 \n',array2)
print('array3 형태 \n',array3)
print('array4 형태 \n',array4)
print('array5 형태 \n',array5)

array1 
 [0 1 2 3 4 5 6 7 8 9]
array2 형태 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 형태 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array4 형태 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
array5 형태 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
